-- GENERATED by supabase/scripts/gen-seed.ts — do not edit by hand.
-- Local-only seed (runs on `supabase db reset`; never reaches the hosted project).

-- Test helper (service role only): the stored location as WKT, so the RLS
-- suite can assert the grid-snapping trigger without exposing coordinates.
-- Lives in the seed so the hosted schema carries no coordinate-reading RPC.
create or replace function public.profile_location_text(profile_id uuid)
returns text
language sql
security definer
set search_path = public
as $$
  select extensions.st_astext(location::extensions.geometry)
    from public.profiles where id = profile_id;
$$;
revoke all on function public.profile_location_text(uuid) from public, anon, authenticated;

-- Six seeded users with real charts (@juno/astro) for the discover
-- screen: five around Istanbul, one in Ankara (outside a 50 km radius).

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-4000-8000-000000000001', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'deniz@seed.local', extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', 'deniz@seed.local', 'email', '{"sub":"00000000-0000-4000-8000-000000000001","email":"deniz@seed.local"}', now(), now(), now())
on conflict (provider_id, provider) do nothing;
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km, consent_version)
values ('00000000-0000-4000-8000-000000000001', 'Deniz', '1993-03-21', '1993-03-21T08:15:00', 745044, '1993-03-21T06:15:00.000Z', '{"version":1,"planets":{"sun":{"longitude":0.6445,"sign":"aries","degree":0.6445,"house":11,"retrograde":false},"moon":{"longitude":338.4356,"sign":"pisces","degree":8.4356,"house":11,"retrograde":false},"mercury":{"longitude":340.3765,"sign":"pisces","degree":10.3765,"house":11,"retrograde":true},"venus":{"longitude":18.0276,"sign":"aries","degree":18.0276,"house":12,"retrograde":true},"mars":{"longitude":104.6576,"sign":"cancer","degree":14.6576,"house":3,"retrograde":false},"jupiter":{"longitude":190.9774,"sign":"libra","degree":10.9774,"house":6,"retrograde":true},"saturn":{"longitude":325.5106,"sign":"aquarius","degree":25.5106,"house":11,"retrograde":false},"uranus":{"longitude":291.6434,"sign":"capricorn","degree":21.6434,"house":9,"retrograde":false},"neptune":{"longitude":290.8604,"sign":"capricorn","degree":20.8604,"house":9,"retrograde":false},"pluto":{"longitude":235.3771,"sign":"scorpio","degree":25.3771,"house":7,"retrograde":true}},"houses":{"ascendant":50.109,"mc":299.3269,"cusps":[50.109,76.9045,98.0593,119.3269,145.322,182.1546,230.109,256.9045,278.0593,299.3269,325.322,2.1546]}}', '{"sun":"aries","moon":"pisces","rising":"taurus"}', 'man', 'women', 'SRID=4326;POINT(29.02 41.03)', 50, '2026-10-01')
on conflict (id) do nothing;

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-4000-8000-000000000002', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'emre@seed.local', extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000002', 'emre@seed.local', 'email', '{"sub":"00000000-0000-4000-8000-000000000002","email":"emre@seed.local"}', now(), now(), now())
on conflict (provider_id, provider) do nothing;
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km, consent_version)
values ('00000000-0000-4000-8000-000000000002', 'Emre', '1996-11-02', '1996-11-02T14:40:00', 745044, '1996-11-02T12:40:00.000Z', '{"version":1,"planets":{"sun":{"longitude":220.3721,"sign":"scorpio","degree":10.3721,"house":8,"retrograde":false},"moon":{"longitude":121.6892,"sign":"leo","degree":1.6892,"house":5,"retrograde":false},"mercury":{"longitude":220.7045,"sign":"scorpio","degree":10.7045,"house":8,"retrograde":false},"venus":{"longitude":184.8674,"sign":"libra","degree":4.8674,"house":7,"retrograde":false},"mars":{"longitude":151.783,"sign":"virgo","degree":1.783,"house":6,"retrograde":false},"jupiter":{"longitude":283.0513,"sign":"capricorn","degree":13.0513,"house":11,"retrograde":false},"saturn":{"longitude":1.4365,"sign":"aries","degree":1.4365,"house":1,"retrograde":true},"uranus":{"longitude":300.8747,"sign":"aquarius","degree":0.8747,"house":11,"retrograde":false},"neptune":{"longitude":295.18,"sign":"capricorn","degree":25.18,"house":11,"retrograde":false},"pluto":{"longitude":242.1217,"sign":"sagittarius","degree":2.1217,"house":9,"retrograde":false}},"houses":{"ascendant":344.4257,"mc":261.7458,"cusps":[344.4257,29.839,59.3778,81.7458,102.7534,127.3835,164.4257,209.839,239.3778,261.7458,282.7534,307.3835]}}', '{"sun":"scorpio","moon":"leo","rising":"pisces"}', 'man', 'everyone', 'SRID=4326;POINT(28.87 41)', 50, '2026-10-01')
on conflict (id) do nothing;

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-4000-8000-000000000003', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'selin@seed.local', extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000003', 'selin@seed.local', 'email', '{"sub":"00000000-0000-4000-8000-000000000003","email":"selin@seed.local"}', now(), now(), now())
on conflict (provider_id, provider) do nothing;
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km, consent_version)
values ('00000000-0000-4000-8000-000000000003', 'Selin', '1994-05-09', '1994-05-09T22:05:00', 745044, '1994-05-09T19:05:00.000Z', '{"version":1,"planets":{"sun":{"longitude":48.9191,"sign":"taurus","degree":18.9191,"house":5,"retrograde":false},"moon":{"longitude":38.964,"sign":"taurus","degree":8.964,"house":5,"retrograde":false},"mercury":{"longitude":59.824,"sign":"taurus","degree":29.824,"house":6,"retrograde":false},"venus":{"longitude":76.4251,"sign":"gemini","degree":16.4251,"house":7,"retrograde":false},"mars":{"longitude":19.2926,"sign":"aries","degree":19.2926,"house":4,"retrograde":false},"jupiter":{"longitude":218.5946,"sign":"scorpio","degree":8.5946,"house":11,"retrograde":true},"saturn":{"longitude":340.8276,"sign":"pisces","degree":10.8276,"house":3,"retrograde":false},"uranus":{"longitude":296.3087,"sign":"capricorn","degree":26.3087,"house":2,"retrograde":true},"neptune":{"longitude":293.2955,"sign":"capricorn","degree":23.2955,"house":2,"retrograde":true},"pluto":{"longitude":236.9165,"sign":"scorpio","degree":26.9165,"house":12,"retrograde":true}},"houses":{"ascendant":253.0277,"mc":182.7942,"cusps":[253.0277,287.1645,326.5827,2.7942,31.1885,53.5607,73.0277,107.1645,146.5827,182.7942,211.1885,233.5607]}}', '{"sun":"taurus","moon":"taurus","rising":"sagittarius"}', 'woman', 'men', 'SRID=4326;POINT(29.1 40.98)', 50, '2026-10-01')
on conflict (id) do nothing;

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-4000-8000-000000000004', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'zeynep@seed.local', extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000004', 'zeynep@seed.local', 'email', '{"sub":"00000000-0000-4000-8000-000000000004","email":"zeynep@seed.local"}', now(), now(), now())
on conflict (provider_id, provider) do nothing;
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km, consent_version)
values ('00000000-0000-4000-8000-000000000004', 'Zeynep', '1998-08-30', '1998-08-30T05:50:00', 745044, '1998-08-30T02:50:00.000Z', '{"version":1,"planets":{"sun":{"longitude":156.5499,"sign":"virgo","degree":6.5499,"house":1,"retrograde":false},"moon":{"longitude":245.492,"sign":"sagittarius","degree":5.492,"house":4,"retrograde":false},"mercury":{"longitude":138.4767,"sign":"leo","degree":18.4767,"house":12,"retrograde":false},"venus":{"longitude":140.5139,"sign":"leo","degree":20.5139,"house":12,"retrograde":false},"mars":{"longitude":125.977,"sign":"leo","degree":5.977,"house":12,"retrograde":false},"jupiter":{"longitude":355.2416,"sign":"pisces","degree":25.2416,"house":8,"retrograde":true},"saturn":{"longitude":33.4487,"sign":"taurus","degree":3.4487,"house":9,"retrograde":true},"uranus":{"longitude":309.7443,"sign":"aquarius","degree":9.7443,"house":6,"retrograde":true},"neptune":{"longitude":299.8493,"sign":"capricorn","degree":29.8493,"house":6,"retrograde":true},"pluto":{"longitude":245.3496,"sign":"sagittarius","degree":5.3496,"house":4,"retrograde":false}},"houses":{"ascendant":148.1445,"mc":51.9666,"cusps":[148.1445,170.9048,198.8509,231.9666,267.1758,299.8109,328.1445,350.9048,18.8509,51.9666,87.1758,119.8109]}}', '{"sun":"virgo","moon":"sagittarius","rising":"leo"}', 'woman', 'everyone', 'SRID=4326;POINT(28.95 41.08)', 50, '2026-10-01')
on conflict (id) do nothing;

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-4000-8000-000000000005', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'kaan@seed.local', extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000005', 'kaan@seed.local', 'email', '{"sub":"00000000-0000-4000-8000-000000000005","email":"kaan@seed.local"}', now(), now(), now())
on conflict (provider_id, provider) do nothing;
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km, consent_version)
values ('00000000-0000-4000-8000-000000000005', 'Kaan', '1991-01-17', '1991-01-17T11:25:00', 745044, '1991-01-17T09:25:00.000Z', '{"version":1,"planets":{"sun":{"longitude":296.7598,"sign":"capricorn","degree":26.7598,"house":10,"retrograde":false},"moon":{"longitude":312.3974,"sign":"aquarius","degree":12.3974,"house":11,"retrograde":false},"mercury":{"longitude":273.294,"sign":"capricorn","degree":3.294,"house":9,"retrograde":false},"venus":{"longitude":315.2555,"sign":"aquarius","degree":15.2555,"house":11,"retrograde":false},"mars":{"longitude":59.2645,"sign":"taurus","degree":29.2645,"house":1,"retrograde":false},"jupiter":{"longitude":130.1151,"sign":"leo","degree":10.1151,"house":5,"retrograde":true},"saturn":{"longitude":297.5966,"sign":"capricorn","degree":27.5966,"house":10,"retrograde":false},"uranus":{"longitude":280.7017,"sign":"capricorn","degree":10.7017,"house":9,"retrograde":false},"neptune":{"longitude":284.7357,"sign":"capricorn","degree":14.7357,"house":9,"retrograde":false},"pluto":{"longitude":230.0006,"sign":"scorpio","degree":20.0006,"house":7,"retrograde":false}},"houses":{"ascendant":28.0295,"mc":285.2093,"cusps":[28.0295,61.2206,84.3504,105.2093,128.5674,160.5612,208.0295,241.2206,264.3504,285.2093,308.5674,340.5612]}}', '{"sun":"capricorn","moon":"aquarius","rising":"aries"}', 'man', 'women', 'SRID=4326;POINT(29.25 40.9)', 50, '2026-10-01')
on conflict (id) do nothing;

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-4000-8000-000000000006', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'burak@seed.local', extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-000000000006', '00000000-0000-4000-8000-000000000006', 'burak@seed.local', 'email', '{"sub":"00000000-0000-4000-8000-000000000006","email":"burak@seed.local"}', now(), now(), now())
on conflict (provider_id, provider) do nothing;
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km, consent_version)
values ('00000000-0000-4000-8000-000000000006', 'Burak', '1995-12-25', '1995-12-25T09:00:00', 323786, '1995-12-25T07:00:00.000Z', '{"version":1,"planets":{"sun":{"longitude":273.0029,"sign":"capricorn","degree":3.0029,"house":11,"retrograde":false},"moon":{"longitude":318.0924,"sign":"aquarius","degree":18.0924,"house":1,"retrograde":false},"mercury":{"longitude":290.1572,"sign":"capricorn","degree":20.1572,"house":12,"retrograde":false},"venus":{"longitude":304.3542,"sign":"aquarius","degree":4.3542,"house":1,"retrograde":false},"mars":{"longitude":288.9521,"sign":"capricorn","degree":18.9521,"house":12,"retrograde":false},"jupiter":{"longitude":267.9542,"sign":"sagittarius","degree":27.9542,"house":11,"retrograde":false},"saturn":{"longitude":348.9758,"sign":"pisces","degree":18.9758,"house":2,"retrograde":false},"uranus":{"longitude":298.9767,"sign":"capricorn","degree":28.9767,"house":12,"retrograde":false},"neptune":{"longitude":294.4359,"sign":"capricorn","degree":24.4359,"house":12,"retrograde":false},"pluto":{"longitude":241.7203,"sign":"sagittarius","degree":1.7203,"house":10,"retrograde":false}},"houses":{"ascendant":301.3608,"mc":233.5658,"cusps":[301.3608,347.3785,25.8965,53.5658,75.6001,96.5352,121.3608,167.3785,205.8965,233.5658,255.6001,276.5352]}}', '{"sun":"capricorn","moon":"aquarius","rising":"aquarius"}', 'man', 'women', 'SRID=4326;POINT(32.85 39.93)', 50, '2026-10-01')
on conflict (id) do nothing;

-- Metrics fixture: an account that never finished onboarding, and three
-- matches made by mutual likes. Read against the views this gives:
--   metrics_onboarding     accounts 7, profiles 6, completion_percent 85.7
--   metrics_matches        matches 3, matches_with_a_message 2
--   metrics_conversations  two_sided 2, two_sided_three_each 1, silent 1

insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-4000-8000-000000000007', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'yarim@seed.local', extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values ('00000000-0000-4000-8000-000000000007', '00000000-0000-4000-8000-000000000007', 'yarim@seed.local', 'email', '{"sub":"00000000-0000-4000-8000-000000000007","email":"yarim@seed.local"}', now(), now(), now())
on conflict (provider_id, provider) do nothing;

-- Deniz and Selin: 6 messages.
insert into public.likes (from_id, to_id, kind, starter_key)
values ('00000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000003', 'like', 'ascendant-conjunction-sun')
on conflict (from_id, to_id) do nothing;
insert into public.likes (from_id, to_id, kind, starter_key)
values ('00000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000001', 'like', 'ascendant-conjunction-sun')
on conflict (from_id, to_id) do nothing;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000001', 'Merhaba! Başlangıç sorusuna ne dersin?'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000001' and m.b = '00000000-0000-4000-8000-000000000003'
   and (select count(*) from public.messages x where x.match_id = m.id) = 0;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000003', 'Bence iyi bir başlangıç :)'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000001' and m.b = '00000000-0000-4000-8000-000000000003'
   and (select count(*) from public.messages x where x.match_id = m.id) = 1;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000001', 'Hafta sonu kahve?'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000001' and m.b = '00000000-0000-4000-8000-000000000003'
   and (select count(*) from public.messages x where x.match_id = m.id) = 2;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000003', 'Olur, cumartesi uyar mı?'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000001' and m.b = '00000000-0000-4000-8000-000000000003'
   and (select count(*) from public.messages x where x.match_id = m.id) = 3;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000001', 'Uyar, Moda olsun.'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000001' and m.b = '00000000-0000-4000-8000-000000000003'
   and (select count(*) from public.messages x where x.match_id = m.id) = 4;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000003', 'Tamam, görüşürüz!'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000001' and m.b = '00000000-0000-4000-8000-000000000003'
   and (select count(*) from public.messages x where x.match_id = m.id) = 5;

-- Emre and Zeynep: 2 messages.
insert into public.likes (from_id, to_id, kind, starter_key)
values ('00000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000004', 'like', 'moon-square-saturn')
on conflict (from_id, to_id) do nothing;
insert into public.likes (from_id, to_id, kind, starter_key)
values ('00000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000002', 'like', 'moon-square-saturn')
on conflict (from_id, to_id) do nothing;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000002', 'Selam, başlangıç sorusu güzelmiş.'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000002' and m.b = '00000000-0000-4000-8000-000000000004'
   and (select count(*) from public.messages x where x.match_id = m.id) = 0;
insert into public.messages (match_id, sender_id, body)
select m.id, '00000000-0000-4000-8000-000000000004', 'Selam! Evet, çok isabetli.'
  from public.matches m where m.a = '00000000-0000-4000-8000-000000000002' and m.b = '00000000-0000-4000-8000-000000000004'
   and (select count(*) from public.messages x where x.match_id = m.id) = 1;

-- Kaan and Zeynep: 0 messages.
insert into public.likes (from_id, to_id, kind, starter_key)
values ('00000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000004', 'like', 'ascendant-trine-ascendant')
on conflict (from_id, to_id) do nothing;
insert into public.likes (from_id, to_id, kind, starter_key)
values ('00000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000005', 'like', 'ascendant-trine-ascendant')
on conflict (from_id, to_id) do nothing;
