import { z } from 'zod';
import { PLANETS, type Planet } from './bodies';
import {
  ASPECTS,
  BODIES,
  OUTER_BODIES,
  type Aspect,
  type Body,
} from './compatibility';

const emitted = (a: Body, b: Body): boolean =>
  !(OUTER_BODIES.has(a) && OUTER_BODIES.has(b));
/**
 * Geometrically impossible in a real chart. Mercury stays within ~28° of
 * the Sun and Venus within ~48°, so with the engine's orbs (sextile needs
 * ≥ 56° separation) only a conjunction can form between the Sun and either;
 * Mercury–Venus can reach 76°, so their sextile is real but square, trine
 * and opposition are not. Such keys are neither emitted nor required.
 */
const IMPOSSIBLE = new Set<string>([
  ...['sextile', 'square', 'trine', 'opposition'].flatMap((asp) => [
    `sun-${asp}-mercury`,
    `sun-${asp}-venus`,
  ]),
  ...['square', 'trine', 'opposition'].map((asp) => `mercury-${asp}-venus`),
]);
import { SIGNS, type Sign } from './signs';
import type { HouseNumber } from './houses';
import bandsRaw from '../content/tr/bands.json';
import dimensionsRaw from '../content/tr/dimensions.json';
import calibrationRaw from '../content/calibration.json';
import placementsRaw from '../content/tr/placements.json';
import titlesRaw from '../content/tr/titles.json';
import elementsRaw from '../content/tr/elements.json';
import housesRaw from '../content/tr/houses.json';
import natalAspectsRaw from '../content/tr/natal-aspects.json';
import retrogradeRaw from '../content/tr/retrograde.json';
import signsRaw from '../content/tr/signs.json';
import synastryRaw from '../content/tr/synastry.json';

/**
 * Turkish interpretation texts. Every key the engine can emit must have a
 * non-empty entry; `content.test.ts` enumerates the key spaces below and
 * fails when one is missing, so a content gap can never reach a screen.
 * Texts are data, not astrology logic: the engine decides which keys apply.
 */
const Snippet = z.string().trim().min(20).max(320);
const SnippetMap = z.record(z.string(), Snippet);
const SynastryEntry = z.object({
  meaning: Snippet,
  question: z.string().trim().min(10).max(200).endsWith('?'),
});

export const RETRO_PLANETS = [
  'mercury',
  'venus',
  'mars',
  'jupiter',
  'saturn',
  'uranus',
  'neptune',
  'pluto',
] as const;
export type RetroPlanet = (typeof RETRO_PLANETS)[number];

export const ELEMENTS = ['fire', 'earth', 'air', 'water'] as const;
export type Element = (typeof ELEMENTS)[number];

/**
 * Four bands, not five, and no verdict in any of them (ADR-0009 §3). The
 * score itself is never printed; this is what reaches a screen.
 */
export const BANDS = ['quiet', 'even', 'strong', 'rare'] as const;
export type Band = (typeof BANDS)[number];

/** Three labels per dimension, cut from that dimension's own distribution. */
export const LEVELS = ['low', 'mid', 'high'] as const;
export type Level = (typeof LEVELS)[number];

const signs = SnippetMap.parse(signsRaw);
const houses = SnippetMap.parse(housesRaw);
const retrograde = SnippetMap.parse(retrogradeRaw);
const natalAspects = SnippetMap.parse(natalAspectsRaw);
const synastry = z.record(z.string(), SynastryEntry).parse(synastryRaw);
const elements = SnippetMap.parse(elementsRaw);
const Label = z.string().trim().min(3).max(40);
const BandEntry = z.object({ name: Label, text: Snippet });
const DimensionEntry = z.object({
  name: Label,
  low: Label,
  mid: Label,
  high: Label,
});
const bands = z.record(z.string(), BandEntry).parse(bandsRaw);
/**
 * The six placements the chart screen leads with, titled by what they mean
 * for dating rather than by the planet's name (PRD amendment 2026-09-10).
 */
export const PRIMARY_PLACEMENTS = [
  'sun',
  'moon',
  'ascendant',
  'mercury',
  'venus',
  'mars',
] as const;
export type PrimaryPlacement = (typeof PRIMARY_PLACEMENTS)[number];
const placements = z.record(z.string(), Label).parse(placementsRaw);
/**
 * Aspect card titles, keyed by dimension and valence rather than by pairing:
 * one table of thirty instead of a title on each of the 255 texts, and the
 * dimension table decides which applies (ADR-0009 §1).
 */
const titles = z.record(z.string(), z.array(Label).length(3)).parse(titlesRaw);
const dimensionLabels = z
  .record(z.string(), DimensionEntry)
  .parse(dimensionsRaw);

/**
 * The calibrated surface, generated by `scripts/score-distribution.ts` and
 * committed: three cut points for the overall bands and two per dimension.
 * Thirteen numbers, and the only place a threshold is allowed to live.
 */
const Calibration = z.object({
  charts: z.number().int().positive(),
  pairs: z.number().int().positive(),
  seed: z.number().int().positive(),
  bands: z.array(z.number()).length(3),
  labels: z.record(z.string(), z.array(z.number()).length(2)),
});
export const CALIBRATION = Calibration.parse(calibrationRaw);

const bodyIndex = (b: Body): number => BODIES.indexOf(b);

/** Canonical (lower BODIES index first) key for a body pair + aspect. */
export function pairKey(a: Body, aspect: Aspect, b: Body): string {
  const [x, y] = bodyIndex(a) <= bodyIndex(b) ? [a, b] : [b, a];
  return `${x}-${aspect}-${y}`;
}

export const signKey = (body: Planet | 'ascendant', sign: Sign): string =>
  `${body}-${sign}`;
export const houseKey = (planet: Planet, house: HouseNumber): string =>
  `${planet}-${house}`;
export const elementKey = (
  luminary: 'sun' | 'moon',
  a: Element,
  b: Element,
): string => {
  const [x, y] = ELEMENTS.indexOf(a) <= ELEMENTS.indexOf(b) ? [a, b] : [b, a];
  return `${luminary}:${x}-${y}`;
};

function must(map: Record<string, string>, key: string, file: string): string {
  const text = map[key];
  if (text === undefined)
    throw new Error(`content/tr/${file}: missing "${key}"`);
  return text;
}

export function signText(body: Planet | 'ascendant', sign: Sign): string {
  return must(signs, signKey(body, sign), 'signs.json');
}

export function houseText(planet: Planet, house: HouseNumber): string {
  return must(houses, houseKey(planet, house), 'houses.json');
}

export function retrogradeText(planet: RetroPlanet): string {
  return must(retrograde, planet, 'retrograde.json');
}

export function natalAspectText(a: Body, aspect: Aspect, b: Body): string {
  return must(natalAspects, pairKey(a, aspect, b), 'natal-aspects.json');
}

export function synastryText(
  a: Body,
  aspect: Aspect,
  b: Body,
): { meaning: string; question: string } {
  const entry = synastry[pairKey(a, aspect, b)];
  if (!entry)
    throw new Error(
      `content/tr/synastry.json: missing "${pairKey(a, aspect, b)}"`,
    );
  return entry;
}

export function elementText(
  luminary: 'sun' | 'moon',
  a: Element,
  b: Element,
): string {
  return must(elements, elementKey(luminary, a, b), 'elements.json');
}

/** Score band per ADR-0003 damping: 50 is "no aspects". */
/**
 * The band a raw score falls in. Cuts come from the committed calibration,
 * never from hand-picked numbers: they are the 25th, 50th and 75th
 * percentiles of the measured population, so the four bands are as near
 * equal as a discrete score allows.
 */
export function bandOf(score: number): Band {
  const [first, second, third] = CALIBRATION.bands;
  if (first === undefined || second === undefined || third === undefined)
    throw new Error('calibration.json has no band cuts');
  if (score < first) return 'quiet';
  if (score < second) return 'even';
  if (score < third) return 'strong';
  return 'rare';
}

export function bandName(score: number): string {
  return mustBand(bandOf(score)).name;
}

export function bandText(score: number): string {
  return mustBand(bandOf(score)).text;
}

function mustBand(band: Band): { name: string; text: string } {
  const entry = bands[band];
  if (entry === undefined) throw new Error(`bands.json has no "${band}"`);
  return entry;
}

/**
 * A dimension's label, or null when the dimension renders absent — no
 * aspect counted into it, element bonus or not (ADR-0009 §2): the bonus is
 * not an aspect, so nothing on screen would explain a label.
 */
export function dimensionLevel(
  dimension: string,
  sums: {
    readonly harmony: number;
    readonly tension: number;
    readonly absolute: number;
    readonly terms: number;
  },
): Level | null {
  if (sums.terms === 0) return null;
  const cuts = CALIBRATION.labels[dimension];
  if (cuts === undefined)
    throw new Error(`calibration.json has no cuts for "${dimension}"`);
  const [low, high] = cuts;
  if (low === undefined || high === undefined)
    throw new Error(`calibration.json has bad cuts for "${dimension}"`);
  // Growth reads the absolute sum: a square to Uranus is signal there, not
  // deficit. The other four read the signed split.
  const value =
    dimension === 'growth'
      ? reduceScore(sums.absolute, 0)
      : reduceScore(sums.harmony, sums.tension);
  if (value < low) return 'low';
  if (value < high) return 'mid';
  return 'high';
}

/** ADR-0003's mapping applied to one dimension's own terms. */
function reduceScore(harmony: number, tension: number): number {
  return 50 + (50 * (harmony - tension)) / (harmony + tension + 10);
}

export function dimensionName(dimension: string): string {
  return mustDimension(dimension).name;
}

export function dimensionLabelText(dimension: string, level: Level): string {
  return mustDimension(dimension)[level];
}

function mustDimension(dimension: string): z.infer<typeof DimensionEntry> {
  const entry = dimensionLabels[dimension];
  if (entry === undefined)
    throw new Error(`dimensions.json has no "${dimension}"`);
  return entry;
}

/** All keys the engine can emit, per file — the completeness contract. */
export const KEY_SPACES = {
  signs: (): string[] => [
    ...PLANETS.flatMap((p) => SIGNS.map((s) => signKey(p, s))),
    ...SIGNS.map((s) => signKey('ascendant', s)),
  ],
  houses: (): string[] =>
    PLANETS.flatMap((p) =>
      ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] as const).map((h) =>
        houseKey(p, h),
      ),
    ),
  retrograde: (): string[] => [...RETRO_PLANETS],
  natalAspects: (): string[] => {
    const keys: string[] = [];
    for (let i = 0; i < BODIES.length; i++) {
      for (let j = i + 1; j < BODIES.length; j++) {
        // why: i and j are bounded by BODIES.length, so both indices resolve
        const a = BODIES[i] ?? 'sun';
        const b = BODIES[j] ?? 'sun';
        if (!emitted(a, b)) continue; // generational pairs are never scored
        for (const aspect of ASPECTS) {
          const key = `${a}-${aspect}-${b}`;
          if (!IMPOSSIBLE.has(key)) keys.push(key);
        }
      }
    }
    return keys;
  },
  synastry: (): string[] => {
    const keys: string[] = [];
    for (let i = 0; i < BODIES.length; i++) {
      for (let j = i; j < BODIES.length; j++) {
        const a = BODIES[i] ?? 'sun';
        const b = BODIES[j] ?? 'sun';
        if (!emitted(a, b)) continue;
        for (const aspect of ASPECTS) keys.push(`${a}-${aspect}-${b}`);
      }
    }
    return keys;
  },
  elements: (): string[] => {
    const keys: string[] = [];
    for (const lum of ['sun', 'moon'] as const) {
      for (let i = 0; i < ELEMENTS.length; i++) {
        for (let j = i; j < ELEMENTS.length; j++) {
          keys.push(`${lum}:${ELEMENTS[i] ?? 'fire'}-${ELEMENTS[j] ?? 'fire'}`);
        }
      }
    }
    return keys;
  },
  bands: (): string[] => [...BANDS],
} as const;

export const IMPOSSIBLE_KEYS: ReadonlySet<string> = IMPOSSIBLE;

export const CONTENT_FILES = {
  signs,
  houses,
  retrograde,
  natalAspects,
  synastry: Object.fromEntries(
    Object.entries(synastry).map(([k, v]) => [k, v.meaning]),
  ),
  elements,
  bands: Object.fromEntries(Object.entries(bands).map(([k, v]) => [k, v.text])),
} as const;

/** "Nasıl seversin" for Venus — the product-language title of a placement. */
export function placementLabel(placement: PrimaryPlacement): string {
  return must(placements, placement, 'placements.json');
}

/**
 * A stable variant index for an aspect, so the same pair always reads the
 * same way. Not random: a title that changed between two visits would look
 * like the chart had changed.
 */
function variantOf(key: string): number {
  let hash = 0;
  for (let i = 0; i < key.length; i++)
    hash = (hash * 31 + key.charCodeAt(i)) % 9973;
  return hash % 3;
}

/**
 * The card title for an inter-chart aspect: "Kolay çekim", "Yüklü kimya".
 * Soft and hard are not good and bad — a square is a dynamic, and the hard
 * titles say what it is rather than judging it (ADR-0009 §1, PRD amendment).
 */
export function aspectTitle(
  dimension: string,
  term: number,
  key: string,
  taken: ReadonlySet<string> = new Set(),
): string {
  const valence = term >= 0 ? 'soft' : 'hard';
  const entry = titles[`${dimension}-${valence}`];
  if (entry === undefined)
    throw new Error(`titles.json has no "${dimension}-${valence}"`);
  // Start at the stable variant, then step on if that title is already on
  // the screen: two cards reading "Anlaşılan taraf" in one section looks
  // like a bug, and there are only three variants per bucket to collide in.
  const start = variantOf(key);
  for (let step = 0; step < entry.length; step++) {
    const choice = entry[(start + step) % entry.length];
    if (choice !== undefined && !taken.has(choice)) return choice;
  }
  const fallback = entry[start];
  if (fallback === undefined) throw new Error('titles.json short of variants');
  return fallback;
}
