/** All Turkish UI strings in one place (PRD: single-language, one file). */
export const t = {
  appName: 'stardate',
  signIn: {
    title: 'Giriş yap',
    emailLabel: 'E-posta adresin',
    emailPlaceholder: 'ornek@eposta.com',
    sendCode: 'Kod gönder',
    codeLabel: 'E-postana gelen 6 haneli kod',
    verify: 'Doğrula',
    sending: 'Gönderiliyor…',
    resend: 'Kodu tekrar gönder',
    consent:
      'Devam ederek doğum bilgilerinin ve konumunun uyum hesaplamak için işlenmesini kabul edersin.',
  },
  onboarding: {
    title: 'Doğum bilgilerin',
    subtitle:
      'Haritanı çıkarmak için yer, tarih ve saat gerekiyor. Saat zorunlu.',
    name: 'Adın',
    gender: 'Cinsiyetin',
    genders: {
      woman: 'Kadın',
      man: 'Erkek',
      unspecified: 'Belirtmek istemiyorum',
    },
    interest: 'Kiminle tanışmak istersin?',
    interests: { women: 'Kadınlar', men: 'Erkekler', everyone: 'Herkes' },
    city: 'Doğum yerin',
    cityPlaceholder: 'Şehir ara…',
    date: 'Doğum tarihin (gün / ay / yıl)',
    time: 'Doğum saatin (saat : dakika)',
    submit: 'Haritamı çıkar',
    computing: 'Hesaplanıyor…',
    errors: {
      name: 'Adını yaz (en fazla 40 karakter).',
      city: 'Listeden bir şehir seç.',
      date: 'Geçerli bir tarih gir.',
      time: 'Doğum saatin gerekli (00:00–23:59).',
      underage: 'stardate 18 yaş ve üzeri içindir.',
      generic: 'Bir şeyler ters gitti, tekrar dene.',
    },
    switchAccount: 'Farklı bir hesapla gir',
    locationHint:
      'Konum izni verirsen mesafeler daha doğru olur; vermezsen doğum şehrin kullanılır.',
  },
  chart: {
    title: 'Doğum haritan',
    bigThree: 'BÜYÜK ÜÇLÜN',
    sun: 'Güneş',
    moon: 'Ay',
    rising: 'Yükselen',
    planets: 'GEZEGENLER',
    house: 'ev',
    retrograde: 'R',
    aspects: 'AÇILAR',
    orb: (deg: string) => `${deg} orb`,
    noAspects:
      'Haritanda majör açı yok; gezegenlerin birbirinden bağımsız çalışıyor.',
    signOut: 'Çıkış yap',
    discover: 'Keşfet ›',
  },
  discover: {
    title: 'Keşfet',
    myChart: 'Haritam',
    settings: 'Ayarlar',
    matches: 'Eşleşmeler',
    scoreLabel: 'uyum',
    like: 'Beğen',
    pass: 'Geç',
    under1km: '1 km altı',
    empty:
      'Yakınlarda şimdilik kimse kalmadı. Yarıçapı ayarlardan genişletebilirsin.',
    noAspect:
      'Bu iki harita arasında ortak bir açı yok; beğeni gönderilemiyor.',
    noAspectWhy: 'Haritalarınız birbirine değmiyor.',
    detail: 'Uyum detayı',
    hideDetail: 'Detayı gizle',
    elements: 'Elementler',
    remaining: (n: number) => (n > 0 ? `${n} kişi daha` : 'Sonuncu'),
  },
  match: {
    // Pre-uppercased: RN textTransform maps Turkish i → I, not İ.
    kicker: 'EŞLEŞTİNİZ',
    title: (name: string) => `${name} ile eşleştin`,
    starterLabel: 'SOHBET BAŞLATICIN',
    noStarter: 'Haritalarınız bir başlangıç cümlesi vermedi; sen bir şey sor.',
    why: 'Neden',
    summary: 'UYUM ÖZETİ',
    elements: 'ELEMENTLER',
    aspects: 'ÖNE ÇIKAN AÇILAR',
    allMatches: 'Tüm eşleşmeler ›',
    backToDiscover: '‹ Keşfete dön',
  },
  matches: {
    title: 'Eşleşmeler',
    empty: 'Henüz eşleşme yok. Keşfetmeye devam et.',
    noMessages: 'Henüz mesaj yok; başlangıç sorusu sende.',
    youPrefix: 'Sen: ',
  },
  chat: {
    backToMatches: '‹ Eşleşmeler',
    viewMatch: 'Uyum detayı ›',
    placeholder: 'Bir şeyler yaz…',
    send: 'Gönder',
    sendFailed: 'Mesaj gönderilemedi, tekrar dene.',
    open: 'Sohbeti aç ›',
  },
  settings: {
    title: 'Ayarlar',
    back: '‹ Keşfet',
    radius: 'Keşif yarıçapı',
    customRadius: (km: number) => `Şu an ${km} km (özel değer).`,
    radiusHint:
      'Bu mesafe içindeki kişiler gösterilir. Konumun başkalarına sadece km olarak görünür.',
    location: 'Konum',
    updateLocation: 'Konumu güncelle',
    locating: 'Konum alınıyor…',
    locationUpdated: 'Konumun güncellendi.',
    locationDenied:
      'Konum alınamadı. Ayarlardan izni açıp tekrar dene; şimdilik kayıtlı konumun değişmedi.',
    locationFailed: 'Konum kaydedilemedi, tekrar dene.',
    locationHint:
      'Konumun ~1 km’lik bir hücreye yuvarlanarak saklanır; kimse tam yerini görmez.',
  },
  common: { loading: 'Yükleniyor…', retry: 'Tekrar dene' },
  errors: {
    generic: 'Bir şeyler ters gitti, tekrar dene.',
    emailInvalid: 'E-posta adresi geçersiz görünüyor.',
    otpInvalid: 'Kod geçersiz ya da süresi dolmuş. Yeni kod iste.',
    rateLimited: 'Çok sık denedin, biraz bekle.',
    alreadyExists: 'Bu kayıt zaten var.',
    invalidData: 'Girdiğin bilgiler kabul edilmedi, kontrol et.',
    notAllowed: 'Bunu yapmaya iznin yok.',
  },
} as const;
