/**
 * Generates supabase/migrations/20260909000010_city_zones.sql: the city →
 * IANA zone mapping the server needs to check a submitted `birth_utc`.
 *
 *   npx tsx supabase/scripts/gen-city-zones.ts
 *
 * The list is the same one the app searches (`packages/geo`), so a city a
 * client can pick is a city the server can resolve. Regenerate whenever
 * that dataset changes; the migration is committed, not built at deploy.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { allCities } from '@juno/geo';

const rows = [...allCities()]
  .map((city) => ({ id: city.id, zone: city.timeZone }))
  .sort((a, b) => a.id - b.id);

const zones = new Set(rows.map((row) => row.zone));
const quote = (value: string): string => `'${value.replaceAll("'", "''")}'`;

const sql = `-- GENERATED by supabase/scripts/gen-city-zones.ts — do not edit by hand.
--
-- The zone of every city the app can offer (${rows.length} cities,
-- ${zones.size} zones), so the server can check a birth instant instead of
-- trusting the device that computed it. A phone with stale tzdata —
-- Android especially — converts a birth time with an offset that was
-- correct years ago, and the whole chart is then wrong by an hour with
-- nothing to show for it.

create table public.city_zones (
  id integer primary key,
  time_zone text not null
);

comment on table public.city_zones is
  'City → IANA zone, generated from packages/geo. Read by the birth check.';

-- Not readable by anyone: the app already has this list offline, and a
-- table with no policies is closed to every client.
alter table public.city_zones enable row level security;

insert into public.city_zones (id, time_zone) values
${rows.map((row) => `  (${row.id}, ${quote(row.zone)})`).join(',\n')};

/**
 * Check a submitted birth instant against the city's zone.
 *
 * Two ways to be right, because a wall clock and an instant do not map
 * one to one:
 *  - the instant renders back to the submitted wall clock in that zone —
 *    the normal case, and the one that accepts both readings of an
 *    ambiguous hour when the clocks go back;
 *  - or it equals what Postgres computes from the wall clock — which is
 *    what a time that never happened (the hour the clocks jump forward)
 *    resolves to.
 * An offset that is simply wrong satisfies neither.
 */
create or replace function public.profiles_check_birth()
returns trigger
language plpgsql
-- Definer: the table is closed to clients (RLS on, no policies), and the
-- check has to read it for every insert.
security definer
set search_path = ''
as $$
declare
  zone text;
begin
  select time_zone into zone
    from public.city_zones where id = new.birth_city_id;
  if zone is null then
    raise exception 'unknown birth city' using errcode = 'check_violation';
  end if;
  if (new.birth_utc at time zone zone) = new.birth_local
     or new.birth_utc = (new.birth_local at time zone zone) then
    return new;
  end if;
  raise exception 'birth_utc does not match the birth city and local time'
    using errcode = 'check_violation';
end;
$$;

create trigger profiles_check_birth
  before insert or update of birth_utc, birth_local, birth_city_id
  on public.profiles
  for each row execute function public.profiles_check_birth();
`;

const out = resolve(
  import.meta.dirname,
  '../migrations/20260909000010_city_zones.sql',
);
writeFileSync(out, sql);
console.log(`wrote ${rows.length} cities (${zones.size} zones) to ${out}`);
