/**
 * Generates supabase/seed.sql: six local-only users with real charts so the
 * discover screen has cards, plus the rows the metrics views are read
 * against (an account that never finished onboarding, three matches and
 * their messages). Deterministic (fixed ids, fixed birth data).
 *
 *   npx tsx supabase/scripts/gen-seed.ts && npx supabase db reset
 *
 * Seeds run only on a local `db reset`; they never reach the hosted project.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  bigThree,
  computeChart,
  isLesserId,
  starterKey,
  toPublicChart,
  type PublicChart,
} from '@juno/astro';
import { resolveBirth } from '@juno/geo';
import { LEGAL_VERSION } from '../../apps/mobile/lib/legal';

const ISTANBUL = 745044;
const ANKARA = 323786;

interface Seed {
  readonly id: string;
  readonly name: string;
  readonly gender: 'woman' | 'man' | 'unspecified';
  readonly interestedIn: 'women' | 'men' | 'everyone';
  readonly cityId: number;
  readonly local: {
    year: number;
    month: number;
    day: number;
    hour: number;
    minute: number;
  };
  /** Where they live now: [longitude, latitude]. */
  readonly home: readonly [number, number];
}

const SEEDS: readonly Seed[] = [
  {
    id: '00000000-0000-4000-8000-000000000001',
    name: 'Deniz',
    gender: 'man',
    interestedIn: 'women',
    cityId: ISTANBUL,
    local: { year: 1993, month: 3, day: 21, hour: 8, minute: 15 },
    home: [29.02, 41.03],
  },
  {
    id: '00000000-0000-4000-8000-000000000002',
    name: 'Emre',
    gender: 'man',
    interestedIn: 'everyone',
    cityId: ISTANBUL,
    local: { year: 1996, month: 11, day: 2, hour: 14, minute: 40 },
    home: [28.87, 41.0],
  },
  {
    id: '00000000-0000-4000-8000-000000000003',
    name: 'Selin',
    gender: 'woman',
    interestedIn: 'men',
    cityId: ISTANBUL,
    local: { year: 1994, month: 5, day: 9, hour: 22, minute: 5 },
    home: [29.1, 40.98],
  },
  {
    id: '00000000-0000-4000-8000-000000000004',
    name: 'Zeynep',
    gender: 'woman',
    interestedIn: 'everyone',
    cityId: ISTANBUL,
    local: { year: 1998, month: 8, day: 30, hour: 5, minute: 50 },
    home: [28.95, 41.08],
  },
  {
    id: '00000000-0000-4000-8000-000000000005',
    name: 'Kaan',
    gender: 'man',
    interestedIn: 'women',
    cityId: ISTANBUL,
    local: { year: 1991, month: 1, day: 17, hour: 11, minute: 25 },
    home: [29.25, 40.9],
  },
  {
    id: '00000000-0000-4000-8000-000000000006',
    name: 'Burak',
    gender: 'man',
    interestedIn: 'women',
    cityId: ANKARA,
    local: { year: 1995, month: 12, day: 25, hour: 9, minute: 0 },
    home: [32.85, 39.93],
  },
];

const pad = (n: number) => String(n).padStart(2, '0');
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** Each seed's birth and chart, computed once: the matches need them too. */
const derived = new Map(
  SEEDS.map((seed) => {
    const birth = resolveBirth({ cityId: seed.cityId, local: seed.local });
    const chart = toPublicChart(
      computeChart({
        utc: birth.utc,
        latitude: birth.latitude,
        longitude: birth.longitude,
      }),
    );
    return [seed.id, { birth, chart }] as const;
  }),
);

function derivedOf(seed: Seed): {
  readonly birth: ReturnType<typeof resolveBirth>;
  readonly chart: PublicChart;
} {
  const found = derived.get(seed.id);
  if (!found) throw new Error(`no birth computed for ${seed.name}`);
  return found;
}

function rows(seed: Seed): string {
  const { birth, chart } = derivedOf(seed);
  const three = bigThree(chart);
  const { local } = seed;
  const date = `${local.year}-${pad(local.month)}-${pad(local.day)}`;
  const email = `${seed.name.toLowerCase()}@seed.local`;
  return `${account(seed.id, email)}
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km, consent_version)
values (${q(seed.id)}, ${q(seed.name)}, ${q(date)}, ${q(`${date}T${pad(local.hour)}:${pad(local.minute)}:00`)}, ${seed.cityId}, ${q(birth.utc.toISOString())}, ${q(JSON.stringify(chart))}, ${q(JSON.stringify(three))}, ${q(seed.gender)}, ${q(seed.interestedIn)}, ${q(`SRID=4326;POINT(${seed.home[0]} ${seed.home[1]})`)}, 50, ${q(CONSENT_VERSION)})
on conflict (id) do nothing;`;
}

/** Imported, not copied: a literal here goes stale the day the notice moves. */
const CONSENT_VERSION = LEGAL_VERSION;

const header = `-- GENERATED by supabase/scripts/gen-seed.ts — do not edit by hand.
-- Local-only seed (runs on \`supabase db reset\`; never reaches the hosted project).

-- Test helper (service role only): the stored location as WKT, so the RLS
-- suite can assert the grid-snapping trigger without exposing coordinates.
-- Lives in the seed so the hosted schema carries no coordinate-reading RPC.
create or replace function public.profile_location_text(profile_id uuid)
returns text
language sql
security definer
set search_path = public
as $$
  select extensions.st_astext(location::extensions.geometry)
    from public.profiles where id = profile_id;
$$;
revoke all on function public.profile_location_text(uuid) from public, anon, authenticated;

-- Six seeded users with real charts (@juno/astro) for the discover
-- screen: five around Istanbul, one in Ankara (outside a 50 km radius).
`;

/**
 * The rows `docs/ROADMAP.md`'s Metrics clause is read against: each view
 * has something to count, and what it should say is written down here
 * and in the seed's own comment, so the manual check has an answer to
 * compare with.
 *
 *   metrics_onboarding     accounts 7, profiles 6, completion_percent 85.7
 *   metrics_matches        matches 3, matches_with_a_message 2
 *   metrics_conversations  two_sided 2, two_sided_three_each 1, silent 1
 *
 * Matches are made the way the app makes them — a like each way with the
 * key `@juno/astro` gives the pair — so a seed user signing in locally
 * sees an ordinary match, not a row the deck still offers.
 */
const UNFINISHED = {
  id: '00000000-0000-4000-8000-000000000007',
  email: 'yarim@seed.local',
};

interface SeedMatch {
  readonly between: readonly [string, string];
  /** In order; each entry is [sender name, body]. */
  readonly messages: readonly (readonly [string, string])[];
}

const MATCHES: readonly SeedMatch[] = [
  {
    between: ['Deniz', 'Selin'],
    messages: [
      ['Deniz', 'Merhaba! Başlangıç sorusuna ne dersin?'],
      ['Selin', 'Bence iyi bir başlangıç :)'],
      ['Deniz', 'Hafta sonu kahve?'],
      ['Selin', 'Olur, cumartesi uyar mı?'],
      ['Deniz', 'Uyar, Moda olsun.'],
      ['Selin', 'Tamam, görüşürüz!'],
    ],
  },
  {
    between: ['Emre', 'Zeynep'],
    messages: [
      ['Emre', 'Selam, başlangıç sorusu güzelmiş.'],
      ['Zeynep', 'Selam! Evet, çok isabetli.'],
    ],
  },
  { between: ['Kaan', 'Zeynep'], messages: [] },
];

function byName(name: string): Seed {
  const seed = SEEDS.find((s) => s.name === name);
  if (!seed) throw new Error(`no seed user named ${name}`);
  return seed;
}

function account(id: string, email: string): string {
  return `
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values (${q(id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(email)}, extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values (${q(id)}, ${q(id)}, ${q(email)}, 'email', ${q(JSON.stringify({ sub: id, email }))}, now(), now(), now())
on conflict (provider_id, provider) do nothing;`;
}

function matchRows(match: SeedMatch): string {
  const [x, y] = match.between.map(byName) as [Seed, Seed];
  const [lo, hi] = isLesserId(x.id, y.id) ? [x, y] : [y, x];
  const key = starterKey(derivedOf(lo).chart, derivedOf(hi).chart);
  if (!key) throw new Error(`${x.name} and ${y.name} share no aspect`);
  const like = (from: Seed, to: Seed) => `
insert into public.likes (from_id, to_id, kind, starter_key)
values (${q(from.id)}, ${q(to.id)}, 'like', ${q(key)})
on conflict (from_id, to_id) do nothing;`;
  const likes = like(x, y) + like(y, x);
  // In order: `messages_server_times` stamps `created_at` with
  // clock_timestamp() row by row, so the thread reads as written even
  // though `db reset` sends the whole seed as one transaction. Guarded
  // like every other row here, so applying the seed twice does not write
  // each conversation twice.
  const messages = match.messages
    .map(
      ([sender, body]) => `
insert into public.messages (match_id, sender_id, body)
select m.id, ${q(byName(sender).id)}, ${q(body)}
  from public.matches m where m.a = ${q(lo.id)} and m.b = ${q(hi.id)}
   and not exists (select 1 from public.messages x where x.match_id = m.id and x.sender_id = ${q(byName(sender).id)} and x.body = ${q(body)});`,
    )
    .join('');
  return `
-- ${x.name} and ${y.name}: ${match.messages.length} messages.${likes}${messages}`;
}

const metrics = `
-- Metrics fixture: an account that never finished onboarding, and three
-- matches made by mutual likes. Read against the views this gives:
--   metrics_onboarding     accounts 7, profiles 6, completion_percent 85.7
--   metrics_matches        matches 3, matches_with_a_message 2
--   metrics_conversations  two_sided 2, two_sided_three_each 1, silent 1
${account(UNFINISHED.id, UNFINISHED.email)}
${MATCHES.map(matchRows).join('\n')}
`;

const out = resolve(import.meta.dirname, '../seed.sql');
writeFileSync(out, header + SEEDS.map(rows).join('\n') + '\n' + metrics);
console.log(
  `wrote ${SEEDS.length} seed users and ${MATCHES.length} matches to ${out}`,
);
