/**
 * Generates supabase/seed.sql: six local-only users with real charts so the
 * discover screen has cards. Deterministic (fixed ids, fixed birth data).
 *
 *   npx tsx supabase/scripts/gen-seed.ts && npx supabase db reset
 *
 * Seeds run only on a local `db reset`; they never reach the hosted project.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { bigThree, computeChart, toPublicChart } from '@stardate/astro';
import { resolveBirth } from '@stardate/geo';

const ISTANBUL = 745044;
const ANKARA = 323786;

interface Seed {
  readonly id: string;
  readonly name: string;
  readonly gender: 'woman' | 'man' | 'unspecified';
  readonly interestedIn: 'women' | 'men' | 'everyone';
  readonly cityId: number;
  readonly local: {
    year: number;
    month: number;
    day: number;
    hour: number;
    minute: number;
  };
  /** Where they live now: [longitude, latitude]. */
  readonly home: readonly [number, number];
}

const SEEDS: readonly Seed[] = [
  {
    id: '00000000-0000-4000-8000-000000000001',
    name: 'Deniz',
    gender: 'man',
    interestedIn: 'women',
    cityId: ISTANBUL,
    local: { year: 1993, month: 3, day: 21, hour: 8, minute: 15 },
    home: [29.02, 41.03],
  },
  {
    id: '00000000-0000-4000-8000-000000000002',
    name: 'Emre',
    gender: 'man',
    interestedIn: 'everyone',
    cityId: ISTANBUL,
    local: { year: 1996, month: 11, day: 2, hour: 14, minute: 40 },
    home: [28.87, 41.0],
  },
  {
    id: '00000000-0000-4000-8000-000000000003',
    name: 'Selin',
    gender: 'woman',
    interestedIn: 'men',
    cityId: ISTANBUL,
    local: { year: 1994, month: 5, day: 9, hour: 22, minute: 5 },
    home: [29.1, 40.98],
  },
  {
    id: '00000000-0000-4000-8000-000000000004',
    name: 'Zeynep',
    gender: 'woman',
    interestedIn: 'everyone',
    cityId: ISTANBUL,
    local: { year: 1998, month: 8, day: 30, hour: 5, minute: 50 },
    home: [28.95, 41.08],
  },
  {
    id: '00000000-0000-4000-8000-000000000005',
    name: 'Kaan',
    gender: 'man',
    interestedIn: 'women',
    cityId: ISTANBUL,
    local: { year: 1991, month: 1, day: 17, hour: 11, minute: 25 },
    home: [29.25, 40.9],
  },
  {
    id: '00000000-0000-4000-8000-000000000006',
    name: 'Burak',
    gender: 'man',
    interestedIn: 'women',
    cityId: ANKARA,
    local: { year: 1995, month: 12, day: 25, hour: 9, minute: 0 },
    home: [32.85, 39.93],
  },
];

const pad = (n: number) => String(n).padStart(2, '0');
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

function rows(seed: Seed): string {
  const birth = resolveBirth({ cityId: seed.cityId, local: seed.local });
  const chart = toPublicChart(
    computeChart({
      utc: birth.utc,
      latitude: birth.latitude,
      longitude: birth.longitude,
    }),
  );
  const three = bigThree(chart);
  const { local } = seed;
  const date = `${local.year}-${pad(local.month)}-${pad(local.day)}`;
  const email = `${seed.name.toLowerCase()}@seed.local`;
  return `
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change_token_new, email_change)
values (${q(seed.id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(email)}, extensions.crypt('seed-password', extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
values (${q(seed.id)}, ${q(seed.id)}, ${q(email)}, 'email', ${q(JSON.stringify({ sub: seed.id, email }))}, now(), now(), now())
on conflict (provider_id, provider) do nothing;
insert into public.profiles (id, display_name, birth_date, birth_local, birth_city_id, birth_utc, chart, big_three, gender, interested_in, location, radius_km)
values (${q(seed.id)}, ${q(seed.name)}, ${q(date)}, ${q(`${date}T${pad(local.hour)}:${pad(local.minute)}:00`)}, ${seed.cityId}, ${q(birth.utc.toISOString())}, ${q(JSON.stringify(chart))}, ${q(JSON.stringify(three))}, ${q(seed.gender)}, ${q(seed.interestedIn)}, ${q(`SRID=4326;POINT(${seed.home[0]} ${seed.home[1]})`)}, 50)
on conflict (id) do nothing;`;
}

const header = `-- GENERATED by supabase/scripts/gen-seed.ts — do not edit by hand.
-- Local-only seed (runs on \`supabase db reset\`; never reaches the hosted project).

-- Test helper (service role only): the stored location as WKT, so the RLS
-- suite can assert the grid-snapping trigger without exposing coordinates.
-- Lives in the seed so the hosted schema carries no coordinate-reading RPC.
create or replace function public.profile_location_text(profile_id uuid)
returns text
language sql
security definer
set search_path = public
as $$
  select extensions.st_astext(location::extensions.geometry)
    from public.profiles where id = profile_id;
$$;
revoke all on function public.profile_location_text(uuid) from public, anon, authenticated;

-- Six seeded users with real charts (@stardate/astro) for the discover
-- screen: five around Istanbul, one in Ankara (outside a 50 km radius).
`;

const out = resolve(import.meta.dirname, '../seed.sql');
writeFileSync(out, header + SEEDS.map(rows).join('\n') + '\n');
console.log(`wrote ${SEEDS.length} seed users to ${out}`);
